/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Material You – Integral Cosméticos Palette
        primary: '#85264b',
        'on-primary': '#ffffff',
        'primary-container': '#ffd9e3',
        'on-primary-container': '#3c0019',
        secondary: '#74565f',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffd9e3',
        'on-secondary-container': '#2b1520',
        tertiary: '#7b5635',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffdcbe',
        'on-tertiary-container': '#2f1500',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        background: '#fff8f8',
        'on-background': '#201a1b',
        surface: '#fff8f8',
        'on-surface': '#201a1b',
        'surface-variant': '#f3dde1',
        'on-surface-variant': '#514347',
        outline: '#837377',
        'outline-variant': '#d6c2c6',
        'surface-1': '#fceef3',
        'surface-2': '#fae6ec',
        'surface-3': '#f8dde5',
        'surface-4': '#f7dbe3',
        'surface-5': '#f5d6df',
        'inverse-surface': '#362024',
        'inverse-on-surface': '#fbedf0',
        'inverse-primary': '#ffb0c9',
        'secondary-fixed': '#ffd9e3',
        'on-secondary-fixed': '#2b1520',
        'secondary-fixed-dim': '#e5bdc7',
        'on-secondary-fixed-variant': '#5b3f48',
        'scrim': '#000000',
      },
      borderRadius: {
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '28px',
      },
      boxShadow: {
        elevation1: '0px 1px 2px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)',
        elevation2: '0px 1px 2px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)',
        elevation3: '0px 4px 8px 3px rgba(0,0,0,0.15), 0px 1px 3px rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
};
