export enum Rol {
  ADMIN = 'ADMIN',
  CAJERO = 'CAJERO',
  BODEGUERO = 'BODEGUERO',
  SUPERVISOR = 'SUPERVISOR',
}

export enum EstadoVenta {
  PENDIENTE = 'PENDIENTE',
  COMPLETADA = 'COMPLETADA',
  ANULADA = 'ANULADA',
  DEVOLUCION = 'DEVOLUCION',
}

export enum MetodoPago {
  EFECTIVO = 'EFECTIVO',
  TARJETA_CREDITO = 'TARJETA_CREDITO',
  TARJETA_DEBITO = 'TARJETA_DEBITO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  COMBINADO = 'COMBINADO',
}

export enum TipoMovimiento {
  ENTRADA = 'ENTRADA',
  SALIDA = 'SALIDA',
  TRASLADO = 'TRASLADO',
  AJUSTE = 'AJUSTE',
  DEVOLUCION = 'DEVOLUCION',
}

export enum EstadoSyncCloud {
  PENDIENTE = 'PENDIENTE',
  SINCRONIZADO = 'SINCRONIZADO',
  ERROR = 'ERROR',
}
